on:
  push:
    branches:
      - master
  pull_request:

name: CI

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.38.0  # MSRV

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions-rs/toolchain@v1
        name: Install toolchain
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        name: Build
        with:
          command: build

      - uses: actions-rs/cargo@v1
        name: Test
        with:
          command: test
          args: --all-features

      - uses: actions-rs/cargo@v1
        name: Check format
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        name: Clippy
        if: matrix.rust == 'stable'
        with:
          command: clippy
          args: -- -D warnings
