name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - nightly
          - beta

    steps:
      - uses: actions-rs/toolchain@v1
        name: Install toolchain
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions-rs/cargo@v1
        name: Build
        with:
          command: build
          args: --all-features

      - uses: actions-rs/cargo@v1
        name: Test
        with:
          command: test
          args: --all-features

      - uses: actions-rs/cargo@v1
        name: Check format
        continue-on-error: true
        if: matrix.rust == 'stable' || matrix.rust == 'nightly'
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        name: Clippy
        if: matrix.rust == 'stable' || matrix.rust == 'nightly'
        with:
          command: clippy
